# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dev_attr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=40)),
                ('unit', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Dev_attr_char',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Dev_attr')),
            ],
        ),
        migrations.CreateModel(
            name='Dev_attr_float',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Dev_attr')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=250)),
                ('manufacturer', models.CharField(max_length=60)),
                ('dtype', models.CharField(max_length=60)),
                ('prod_date', models.DateField(max_length=60)),
                ('serial_number', models.CharField(max_length=50)),
                ('tag_name', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Device')),
            ],
        ),
        migrations.AddField(
            model_name='dev_attr_float',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device'),
        ),
        migrations.AddField(
            model_name='dev_attr_char',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device'),
        ),
    ]
