# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_d', models.CharField(choices=[('A', 'Area'), ('D', 'Device')], max_length=1)),
                ('name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=250)),
                ('manufacturer', models.CharField(max_length=60)),
                ('dtype', models.CharField(max_length=60)),
                ('prod_date', models.DateField(max_length=60)),
                ('serial_number', models.CharField(max_length=50)),
                ('tag_name', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.AreaDevice')),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='parent',
        ),
        migrations.AlterField(
            model_name='dev_attr_char',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.AreaDevice'),
        ),
        migrations.AlterField(
            model_name='dev_attr_float',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.AreaDevice'),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
